Feat/challenge functions 1
ZilongZhan/Javascript-functions pull request #1
Opened 2023-11-18 17:34 UTC by ZilongZhan

2023-11-18 17:38 UTC, ZilongZhan commented
Accidentally pushed a folder within a folder. Sorry

2023-11-19 19:24 UTC, tictools requested changes

2023-11-19 19:24 UTC, tictools commented on exercise_01/getDistanceFromThreshold.js
> +const getDistanceFromThreshold = function (value, threshold) {
This function should return a number but it returns a string... 🤔

FIX: needs work

2023-11-19 19:24 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
> +function checkCollectionHasElements(collection) {
There is an easier way to define this logic.

FIX: needs work

2023-11-19 19:24 UTC, tictools commented on exercise_02/index.js
> +console.log(getTotalWordsFromString("penis")); //5
Avoid this kind of words when coding

2023-11-20 18:36 UTC, adrianagrd approved these changes
Good work! :)

2023-11-21 07:36 UTC, tictools approved these changes

2023-11-21 15:26 UTC, merged